Fixed: Leading - character in passphrase broke hostapd

diff --git a/wlanpi-server/server_switcher b/wlanpi-server/server_switcher
--- a/wlanpi-server/server_switcher
+++ b/wlanpi-server/server_switcher
@@ -10,8 +10,8 @@ set -e
 
 NAME=server_switcher
 DESC="Script to switch server mode on/off"
-VERSION=0.01
 STATUS_FILE="/etc/wlanpi-state"
+SERVER_CONF_FILE="/etc/wlanpi-server/conf/hostapd.conf"
 
 if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
@@ -30,42 +30,47 @@ fi
 # 5. Reboot the WLAN Pi to ensure clean activation
 #
 ###############################################################################
+
 server_on () {
 
-  echo "Starting switch from classic mode to server mode"
+  echo "Starting switch from Classic mode to Server mode"
 
   # check what state the WLAN Pi is in classic mode
   PI_STATUS=`cat $STATUS_FILE | grep 'classic'` || true
   if  [ -z "$PI_STATUS" ]; then
-     echo "Failed - WLAN Pi is not in classic mode."
+     echo "Failed: WLAN Pi is not in Classic mode"
      exit 1
   fi
 
-  echo "Creating a unique SSID"
-  # Get the last 3 chars of eth0 MAC address
-  LAST_3_CHARS_MAC=$(sed s/://g /sys/class/net/eth0/address | grep -o '...$')
-  # Check if we got 3 chars
-  if [ ${#LAST_3_CHARS_MAC} -ne 3 ]; then
-    echo "Failed parsing eth0 MAC address during unique SSID creation"
-    exit 1
-  fi
-  # Configure the unique SSID
-  if grep -q -E "^?ssid=" /etc/wlanpi-server/conf/hostapd.conf; then
-    sudo sed -i "s/^#\?ssid=.*/ssid=WLAN Pi Server $LAST_3_CHARS_MAC/" /etc/wlanpi-server/conf/hostapd.conf
-  else
-    echo "ssid=WLAN Pi Server $LAST_3_CHARS_MAC" >> /etc/wlanpi-server/conf/hostapd.conf
-  fi
-
-  echo "Generating a random WPA2 passphrase"
-  PASSPHRASE=$(tr -dc 'A-Ha-h2-9-J-Kj-k2-9-M-Nm-n2-9-P-Zp-z2-9' </dev/urandom | head -c 12  ; echo)
-  # Only generate a random passphrase if the user has not configured their own one
-  if grep -q -E "^?wpa_passphrase=wifipros" /etc/wlanpi-server/conf/hostapd.conf; then
-    sudo sed -i "s/^#\?wpa_passphrase=.*/wpa_passphrase=$PASSPHRASE/" /etc/wlanpi-server/conf/hostapd.conf
+  # Check if we are using the factory shipped SSID, rename if we are
+  echo "Checking for factory default SSID name ..."
+  if grep -q -E "^?ssid=wlanpi_server" $SERVER_CONF_FILE; then
+    echo "Creating a unique SSID ..."
+    # Get the last 3 chars of eth0 MAC address
+    LAST_3_CHARS_MAC=$(sed s/://g /sys/class/net/eth0/address | grep -o '...$')
+    # Check if we got 3 chars
+    if [ ${#LAST_3_CHARS_MAC} -ne 3 ]; then
+      echo "Failed parsing eth0 MAC address during unique SSID creation"
+      exit 1
+    fi
+    # Configure the unique SSID
+    if grep -q -E "^?ssid=" $SERVER_CONF_FILE; then
+     sed -i "s/^#\?ssid=.*/ssid=WLAN Pi Server $LAST_3_CHARS_MAC/" $SERVER_CONF_FILE
+    else
+      echo "ssid=WLAN Pi Server $LAST_3_CHARS_MAC" >> $SERVER_CONF_FILE
+    fi
   fi
 
-  echo "Enabling server mode..."
+  # Generate a random passphrase if the user has not configured their own one
+  if grep -q -E "^?wpa_passphrase=wifipros" $SERVER_CONF_FILE; then
+    echo "Generating a new random WPA2 passphrase ..."
+    PASSPHRASE=$(tr -dc 'A-Ha-h2-9J-Kj-k2-9M-Nm-n2-9P-Zp-z2-9' </dev/urandom | head -c 12  ; echo)
+    sed -i "s/^#\?wpa_passphrase=.*/wpa_passphrase=$PASSPHRASE/" $SERVER_CONF_FILE
+  fi
+
+  echo "Enabling server mode ..."
   #Backup existing config files
-  echo "Backing up existing config files..."
+  echo "Backing up existing config files ..."
   cp /etc/default/isc-dhcp-server /etc/default/isc-dhcp-server.serv
   cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.serv
   cp /etc/network/interfaces /etc/network/interfaces.serv
@@ -80,7 +85,7 @@ server_on () {
     cp /etc/ser2net.conf /etc/ser2net.conf.serv
   fi
   # Remove existing config files
-  echo "Removing existing config files..."
+  echo "Removing existing config files ..."
   rm /etc/default/isc-dhcp-server
   rm /etc/dhcp/dhcpd.conf
   rm /etc/network/interfaces
@@ -137,6 +142,7 @@ server_on () {
 # 5. Reboot wlanpi to provide clean restoration of services
 #
 ###############################################################################
+
 server_off () {
 
   # check what state the WLAN Pi is in
@@ -149,7 +155,7 @@ server_off () {
   echo "Starting switch from server mode to classic mode"
 
   # Remove links to config files
-  echo "Removing links to config files..."
+  echo "Removing links to config files ..."
   unlink /etc/default/isc-dhcp-server
   unlink /etc/dhcp/dhcpd.conf
   unlink /etc/network/interfaces
@@ -160,7 +166,7 @@ server_off () {
   unlink /etc/ser2net.conf
 
   # Restore original config files
-  echo "Restoring original config files..."
+  echo "Restoring original config files ..."
   cp /etc/default/isc-dhcp-server.serv /etc/default/isc-dhcp-server
   cp /etc/dhcp/dhcpd.conf.serv /etc/dhcp/dhcpd.conf
   cp /etc/network/interfaces.serv /etc/network/interfaces
@@ -207,10 +213,9 @@ status () {
 }
 
 version () {
-    N=/etc/wlanpi-server/$NAME
-        echo "Version: $N $VERSION" >&2
-        exit 1
-
+  VERSION=$(apt list --installed wlanpi-server 2>/dev/null | grep wlanpi-server | awk '{print $2}')
+  echo "Version: $VERSION" >&2
+  exit 0
 }
 
 case "$1" in
